export type PropertyValue = string | number | boolean;

/**
 * Keys the runner owns, mapped to what controls them. A config that sets one of these is rejected,
 * because the runner would either not find its world or could not run `/gametest`.
 */
export const MANAGED_PROPERTIES: ReadonlyMap<string, string> = new Map([
  ['level-name', 'the runner'],
  ['server-port', '--port'],
  ['server-portv6', '--port'],
  ['allow-cheats', 'the runner; /gametest needs it'],
  ['online-mode', 'the runner; no Xbox Live sign-in'],
]);

export interface ServerPropertiesOptions {
  levelName: string;
  port: number;
  portV6: number;

  /** The script watchdog hang threshold in milliseconds, raised so long-running suites are not killed. */
  watchdogHangMs: number;

  /**
   * Advertise the server on the local network so it appears in a client's Friends tab. Forced on
   * when the server is held open for a person to join.
   */
  lanVisible: boolean;

  /** From the project's config file. Applied over the runner's defaults; managed keys are rejected. */
  overrides?: Record<string, PropertyValue>;
}

/** The `server.properties` the runner writes before every run. Unlisted keys keep the shipped default. */
export function renderServerProperties(options: ServerPropertiesOptions): string {
  const { levelName, port, portV6, watchdogHangMs, lanVisible, overrides = {} } = options;

  for (const key of Object.keys(overrides)) {
    const owner = MANAGED_PROPERTIES.get(key);

    if (owner) {
      throw new Error(`server property "${key}" is managed by ${owner} and cannot be set in the config file`);
    }
  }

  const defaults: Record<string, PropertyValue> = {
    'server-name': 'bc-bds-runner',

    // Creative + peaceful so nothing wanders into a test plot and no mob AI competes for ticks.
    'gamemode': 'creative',
    'force-gamemode': true,
    'difficulty': 'peaceful',

    'default-player-permission-level': 'operator',
    'allow-list': false,

    // Small world, few threads: the tests run in one plot and the rest is wasted simulation.
    'view-distance': 5,
    'tick-distance': 4,
    'max-threads': 4,
    'max-players': 1,

    // Never kick for idleness; there is no player, and a timeout mid-run would look like a hang.
    'player-idle-timeout': 0,

    // A second copy of everything on disk, for when stdout is buffered oddly under CI.
    'content-log-file-enabled': true,
    'content-log-file-max-size-bytes': 33554432,

    'script-watchdog-hang-threshold': watchdogHangMs,

    // A hung script must fail the run, not take the server down before it can report anything.
    'script-watchdog-enable-shutdown': false,

    'enable-lan-visibility': false,
  };

  const managed: Record<string, PropertyValue> = {
    'level-name': levelName,
    'server-port': port,
    'server-portv6': portV6,
    'allow-cheats': true,
    'online-mode': false,
  };

  const merged: Record<string, PropertyValue> = { ...defaults, ...overrides, ...managed };

  if (lanVisible) { merged['enable-lan-visibility'] = true; }

  const header = [
    '# Generated by @bedrock-core/bds-runner before each run. Edits here are overwritten;',
    '# set "properties" in bds-runner.json instead.',
    '# The world (worlds/<level-name>) is bootstrapped once per BDS version and then reused.',
    '',
  ];

  return [...header, ...Object.entries(merged).map(([key, value]) => `${key}=${value}`), ''].join('\n');
}
