/** The `server.properties` the runner writes before every run. Unlisted keys keep the shipped default. */
export interface ServerPropertiesOptions {
  levelName: string;
  port: number;
  portV6: number;

  /** The script watchdog hang threshold in milliseconds, raised so long-running suites are not killed. */
  watchdogHangMs: number;

  /**
   * Advertise the server on the local network so it appears in a client's Friends tab.
   *
   * Off for an unattended run, where two servers on one machine must not fight over discovery. On
   * when the server is held open for a person to join and look at the test plots.
   */
  lanVisible: boolean;
}

export function renderServerProperties(options: ServerPropertiesOptions): string {
  const { levelName, port, portV6, watchdogHangMs, lanVisible } = options;

  const lines: [string, string | number][] = [
    ['level-name', levelName],
    ['server-name', 'bc-bds-runner'],

    // Creative + peaceful so nothing wanders into a test plot and no mob AI competes for ticks.
    ['gamemode', 'creative'],
    ['force-gamemode', 'true'],
    ['difficulty', 'peaceful'],

    // `/gametest` needs cheats and permission level >= 1. The console is level 4 regardless, but a
    // world without cheats refuses the command outright.
    ['allow-cheats', 'true'],
    ['default-player-permission-level', 'operator'],

    // No auth, no allowlist: nobody connects to this server, and requiring Xbox Live sign-in would
    // make CI depend on an external service.
    ['online-mode', 'false'],
    ['allow-list', 'false'],

    ['enable-lan-visibility', lanVisible ? 'true' : 'false'],
    ['server-port', port],
    ['server-portv6', portV6],

    // Small world, few threads: the tests run in one plot and the rest is wasted simulation.
    ['view-distance', 5],
    ['tick-distance', 4],
    ['max-threads', 4],
    ['max-players', 1],

    // Never kick for idleness — there is no player, and a timeout mid-run would look like a hang.
    ['player-idle-timeout', 0],

    // A second copy of everything on disk, for when stdout is buffered oddly under CI.
    ['content-log-file-enabled', 'true'],
    ['content-log-file-max-size-bytes', 33554432],

    ['script-watchdog-hang-threshold', watchdogHangMs],

    // A hung script must fail the run, not take the server down before it can report anything.
    ['script-watchdog-enable-shutdown', 'false'],
  ];

  const header = [
    '# Generated by @bedrock-core/bds-runner before each run. Edits here are overwritten.',
    '# The world (worlds/<level-name>) is bootstrapped once per BDS version and then reused.',
    '',
  ];

  return [...header, ...lines.map(([key, value]) => `${key}=${value}`), ''].join('\n');
}
